name: Build Amd64 Image
on:
   push:
    branches:
      - master
      - main
jobs:
  build:
      runs-on: ubuntu-latest
      name: Build image job
      steps:
          - name: Checkout master
            uses: actions/checkout@master
          - name: Build and publish image
            uses: ilteoood/docker_buildx@master
            with:
              publish: false
              imageName: test
              platform: linux/amd64,linux/arm64
              tag: latest # 默认latest，可以针对平台，修改tag
